### ISSUE TITLE
ERROR Plugin load failed: hexo-related-posts Error: Cannot find module 'natural'

### ISSUE THREAD

**Issue by darrenclover** [sergeyzwezdin/hexo-related-posts#1]
ERROR Plugin load failed: hexo-related-posts
Error: Cannot find module 'natural'
what should i do？

**Comment by sergeyzwezdin** [comment]
@darrenclover thank you for the report. I'll check.

**Comment by sergeyzwezdin** [comment]
@darrenclover Try to update to the latest version

```bash
$ npm add hexo-related-posts@latest
```

Should be ok now.
