### ISSUE TITLE
Incompatible with hexo 7.0

### ISSUE THREAD

**Issue by pplmx** [sergeyzwezdin/hexo-related-posts#18]
Here is the error log:

<details>
<summary>npm i error</summary>

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: caoyu.info@1.0.0
npm ERR! Found: hexo@7.0.0
npm ERR! node_modules/hexo
npm ERR!   hexo@"7.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer hexo@"^4.2.0 || ^5.2.0 || ^6.3.0" from hexo-related-posts@1.5.1
npm ERR! node_modules/hexo-related-posts
npm ERR!   hexo-related-posts@"^1.5.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

</details>

**Comment by ajimix** [comment]
I'm having the same issue

**Comment by Atif-Sheikh** [comment]
Same issue.

cc: @sergeyzwezdin

**Comment by sergeyzwezdin** [comment]
@pplmx you can test it with Hexo 7 and if it works correctly, please create PR to update deps.

**Comment by Atif-Sheikh** [comment]
@sergeyzwezdin Done.

https://github.com/sergeyzwezdin/hexo-related-posts/pull/20

**Comment by Atif-Sheikh** [comment]
@sergeyzwezdin I've tested the package with Hexo 7 locally in my project, and everything seems to be working fine. Could you please take a look at the [PR](https://github.com/sergeyzwezdin/hexo-related-posts/pull/20) and review it?

**Comment by sergeyzwezdin** [comment]
@Atif-Sheikh thank you for your efforts! 🚀 I've merged it and published.
