### ISSUE TITLE
 npm resolution error report

### ISSUE THREAD

**Issue by hanqunfeng** [sergeyzwezdin/hexo-related-posts#19]
# npm resolution error report

2024-01-05T02:12:55.069Z

While resolving: hexo-site@0.0.0
Found: hexo@7.0.0
node_modules/hexo
  hexo@"^7.0.0" from the root project

Could not resolve dependency:
peer hexo@"^4.2.0 || ^5.2.0 || ^6.3.0" from hexo-related-posts@1.5.1
node_modules/hexo-related-posts
  hexo-related-posts@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by sergeyzwezdin** [comment]
Related #18
