### ISSUE TITLE
Incompatible with hexo 6.0

### ISSUE THREAD

**Issue by wangjiezhe** [sergeyzwezdin/hexo-related-posts#8]
When I use it with hexo 6.0, the installation reports an error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hexo-site@0.0.0
npm ERR! Found: hexo@6.0.0
npm ERR! node_modules/hexo
npm ERR!   hexo@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer hexo@"^4.2.0 || ^5.2.0" from hexo-related-posts@1.5.0
npm ERR! node_modules/hexo-related-posts
npm ERR!   hexo-related-posts@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by ajimix** [comment]
same here

**Comment by sergeyzwezdin** [comment]
I'll take a look, but no ETA for the moment.

**Comment by yoshi0808** [comment]
FYI
refer to the below link issue;
https://github.com/next-theme/hexo-theme-next/issues/461

**Comment by ajimix** [comment]
@sergeyzwezdin any plans to make it compatible? I guess it might be some minimal change and there are several themes depending on it

**Comment by leeUWU** [comment]
Same

**Comment by sergeyzwezdin** [comment]
@yoshi0808 @yoshi0808 @ajimix If you guys will be able to craft PR for than, I'm more than happy to merge it.

**Comment by panqiincs** [comment]
I hope you guys can fix this bug, it will save my PV, many thanks!

**Comment by ajimix** [comment]
@sergeyzwezdin here is it https://github.com/sergeyzwezdin/hexo-related-posts/pull/12

**Comment by sergeyzwezdin** [comment]
@ajimix done, thanks!
